services:
  db:
    image: postgres:18
    container_name: shortener_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: shortener_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: shortener_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

volumes:
  postgres_data: