"""add is_custom flag to urls

Revision ID: 70236a77f1ed
Revises: e0ea782f5e61
Create Date: 2026-09-03 01:40:18.187144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70236a77f1ed'
down_revision: Union[str, Sequence[str], None] = 'e0ea782f5e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_custom', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'is_custom')
    # ### end Alembic commands ###
